/*
 * Swagger Clients server
 *
 * This is a sample server Clients server
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/v2/",
		Index,
	},

	Route{
		"AddClient",
		strings.ToUpper("Post"),
		"/v2/clients",
		AddClient,
	},

	Route{
		"DeleteClient",
		strings.ToUpper("Delete"),
		"/v2/clients/{clientId}",
		DeleteClient,
	},

	Route{
		"GetClientById",
		strings.ToUpper("Get"),
		"/v2/clients/{clientId}",
		GetClientById,
	},

	Route{
		"UpdateClient",
		strings.ToUpper("Put"),
		"/v2/clients",
		UpdateClient,
	},

	Route{
		"UpdateClientWithForm",
		strings.ToUpper("Post"),
		"/v2/clients/{clientId}",
		UpdateClientWithForm,
	},
}
